### ISSUE TITLE
Change the project plan according to feedback

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#71]
Our project plan has received some feedback. The issues mentioned don't require too much work, but should be solved asap. Details of the feedback can be found [here](https://piazza.com/class/jrg99tkfke706?cid=110).

**Comment by leventbass** [comment]
I have revised the project plan upon customer feedback and also added new project plan details regarding:
- [ ] Initialization of back-end part of our application
- [ ] Initialization of front-end part of our application
- [ ] Sign up/login functionality
- [ ] Search for trading equipment functionality
- [ ] View trading equipment and events functionality
- [ ] Draft for front-end  
- [ ] API testing
- [ ] API deployment
- [ ] Future assignments

**Comment by leventbass** [comment]
Project plan will be revised regularly. For now, I'm closing this issue.
